export const portfolioData = [
  { img: "/assets/portfolio/image1.png", link: "https://calbuygh.com" },
  { img: "/assets/portfolio/image2.png", link: "https://rehobothflorals.com" },
  { img: "/assets/portfolio/image3.png", link: "https://swaghasports.com" },
  {
    img: "/assets/portfolio/image4.png",
    link: "https://ricairtravel.com",
  },
  {
    img: "/assets/portfolio/image5.png",
    link: "https://space-tourism-two-pied.vercel.app/",
  },
  {
    img: "/assets/portfolio/image6.png",
    link: "https://google-gemini-chatbot-chi.vercel.app/",
  },
  {
    img: "/assets/portfolio/image7.png",
    link: "https://google-gemini-chatbot-rtge.vercel.app/",
  },
  {
    img: "/assets/portfolio/image8.png",
    link: "https://google-gemini-chatbot-rtge.vercel.app/",
  },
  {
    img: "/assets/portfolio/image9.png",
    link: "https://github.com/shekinahwebdev/NIMBUS",
  },
];

export const projects = [
  {
    title: "CalBuy Modern E-commerce Site",
    category: "E-Commerce",
    img: "/assets/portfolio/image1.png",
    desc: "A production-ready e-commerce web application built with a modern UI, real-time store integration, and secure payment workflows.",
    color: "#3b82f6",
    stack: ["React", "Redux", "Tailwind", "RestApi", "React Router"],
    liveLink: "https://calbuygh.com",
    sourceLink: "https://github.com/shekinahwebdev/CAL-BUY-SHOP",
    features: [
      "Real Store API Integration for Products, Images, and Pricing",
      "Secure Online Payments with Stripe",
      "User Authentication with Email Verification",
      "Real-time Cart and Inventory Synchronization",
      "Dynamic Product Filtering and Category Navigation",
      "Guest and Authenticated Checkout Flow",
      "Order History and Transaction Tracking",
    ],
  },
  {
    title: "Swagha Sports",
    category: "Entertainment",
    img: "/assets/portfolio/image3.png",
    desc: "A modern sports and media platform built to showcase team activities, match updates, and engaging content with smooth animations and seamless navigation.",
    color: "#8b5cf6",
    stack: [
      "React",
      "Framer Motion",
      "React Router",
      "REST API",
      "Node.js",
      "Resend",
    ],
    liveLink: "https://swaghasports.com",
    sourceLink: "https://github.com/shekinahwebdev/SWAGHA-SOCCER-CLUB",
    features: [
      "Dynamic Sports Content Powered by a REST API",
      "Smooth Page Transitions and Animations with Framer Motion",
      "Email Notifications and Contact Forms via Resend",
      "Client-Side Routing for a Seamless Single-Page Experience",
      "Responsive, Mobile-First UI Design",
      "Backend Integration for Content Management and Updates",
    ],
  },
  {
    title: "Rehoboth Florals",
    category: "E-Commerce",
    img: "/assets/portfolio/image2.png",
    desc: "A full-featured floral e-commerce platform designed with a modern UI, smooth user flow, and backend support for real-world store operations.",
    color: "#ec4899",
    stack: [
      "React",
      "Tailwind CSS",
      "shadcn/ui",
      "Context API",
      "Node.js",
      "REST API",
      "Vite",
    ],
    liveLink: "https://rehobothflorals.com",
    sourceLink: "https://github.com/shekinahwebdev/REHOBOTH-FLORAL-WEBSITE",
    features: [
      "Real Product Management via Backend API",
      "Image Upload and Storage for Product Listings",
      "Cart and Checkout Flow Integrated with Stripe",
      "Dynamic Product Rendering from Live Store Data",
      "Reusable UI Components Built with shadcn/ui",
      "Responsive and Accessible User Interface",
    ],
  },
  {
    title: "Ricair Travel Site",
    category: "Travel",
    img: "/assets/portfolio/image4.png",
    desc: "A modern travel consultation website built with a clean interface, dynamic content, and backend-powered inquiry and communication features.",
    color: "#22c55e",
    stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "REST API",
      "Resend",
    ],
    liveLink: "https://ricairtravel.com",
    sourceLink: "https://github.com/shekinahwebdev/RICAIR-TRAVEL-CONSULT",
    features: [
      "Backend-Powered Contact and Booking Inquiry Forms",
      "Email Notifications and Client Communication via Resend",
      "Dynamic Destination and Travel Content Rendering",
      "Form Validation and Secure API Handling",
      "Responsive, Mobile-First UI Design",
    ],
  },
  {
    title: "Space Tourism Experience",
    category: "UI / Animation",
    img: "/assets/portfolio/image5.png",
    desc: "An immersive space tourism web experience focused on smooth animations, interactive transitions, and a visually engaging user interface.",
    color: "#22c55e",
    stack: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Vite"],
    liveLink: "https://space-tourism-two-pied.vercel.app/",
    sourceLink: "https://github.com/shekinahwebdev/SPACE-TOURISM",
    features: [
      "Smooth Page Transitions and Micro-Interactions",
      "Scroll-Based and Triggered Animations",
      "Interactive Navigation with Motion Feedback",
      "Responsive Layout with Consistent Animation Flow",
      "Pixel-Perfect UI Implementation from Design Specs",
    ],
  },

  {
    title: "AI ChatBot",
    category: "AI / Frontend",
    img: "/assets/portfolio/image6.png",
    desc: "A conversational AI web application that allows users to interact with a Gemini-powered chatbot, featuring real-time messaging, intelligent responses, and a sleek, responsive interface.",
    color: "#f59e0b",
    stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "OpenAI / Gemini API",
      "Vite",
    ],
    liveLink: "https://google-gemini-chatbot-chi.vercel.app/",
    sourceLink: "https://github.com/shekinahwebdev/AI-CHATBOT",
    features: [
      "Real-Time AI Chat with Gemini/OpenAI API",
      "Dynamic Message Rendering with Typing Animations",
      "Context-Aware Conversations with Session Persistence",
      "Responsive, Mobile-First UI Design",
      "Customizable Chat Interface with Smooth Animations",
    ],
  },

  {
    title: "Gemini AI ChatBot Clone",
    category: "AI / Fullstack",
    img: "/assets/portfolio/image7.png",
    desc: "A fully functional Gemini AI chatbot clone that lets users engage in real-time, context-aware conversations powered by Gemini AI, featuring live response generation and a smooth interactive interface.",
    color: "#f97316",
    stack: ["Html", "Css", "Javascript", "OpenAI / Gemini API", "Vite"],
    liveLink: "https://google-gemini-chatbot-rtge.vercel.app/",
    sourceLink: "https://github.com/shekinahwebdev/GEMINI-CHATBOT-CLONE",
    features: [
      "Real-Time AI Chat with Gemini/OpenAI API",
      "Context-Aware Conversations with Session Memory",
      "Dynamic Typing Animations and Smooth UI Interactions",
      "Backend Integration for Persistent Chat Sessions",
      "Mobile-Responsive Design with Dark/Light Mode",
    ],
  },
  {
    title: "ShekCodes Portfolio",
    category: "Portfolio",
    img: "/assets/portfolio/image8.png",
    desc: "My personal portfolio showcasing all my frontend and fullstack projects, interactive UI/UX work, and real-world applications built with modern web technologies.",
    color: "#0ea5e9",
    stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Vite",
      "Framer Motion",
      "React Router",
    ],
    liveLink: "https://shekcodes.vercel.app/",
    sourceLink: "https://github.com/shekinahwebdev/SHEKCODES",
    features: [
      "Showcases all personal and client projects",
      "Dynamic filtering and project categorization",
      "Interactive UI with animations using Framer Motion",
      "Mobile-first responsive design",
      "Clean code architecture and modern tech stack",
    ],
  },
  {
    title: "Nimbus CMS",
    category: "CMS",
    img: "/assets/portfolio/image9.png",
    desc: "Nimbus is a lightweight admin panel for single users, offering real-time content management with a sleek interface. Users can edit text, manage images, and update pages with ease, powered by a Firebase backend for authentication and data storage.",
    color: "0ea5e9",
    stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Router",
      "Firebase",
    ],
    liveLink: "https://github.com/shekinahwebdev/NIMBUS",
    sourceLink: "https://github.com/shekinahwebdev/NIMBUS",
    features: [
      "Secure login page with Firebase Authentication",
      "Dashboard overview displaying key site stats",
      "Page-based editor with sidebar navigation (Home, About, Services, Contact)",
      "Edit text fields, upload and replace images, and update content in real-time",
      "Save & Publish button to instantly update site content",
      "Simple, intuitive sidebar navigation",
      "Responsive and mobile-friendly design",
      "Smooth animations using Framer Motion",
    ],
  },
];

export const aiTools = [
  {
    name: "Cursor",
    role: "IDE",
    desc: "The AI-native code editor that handles complex refactors.",
    icon: "⚡",
  },
  {
    name: "v0.dev",
    role: "UI Generation",
    desc: "Shifting from design to code in seconds using generative UI.",
    icon: "🎨",
  },
];
